### ISSUE TITLE
Authorization.

### ISSUE THREAD

**Issue by Snorri1986** [Snorri1986/MyVehicleServiceApp#13]
DB side:
1. On db side - create function which check inserted login and password 
and resturns 0 - success, -1 - incorrect login or password/user not found;
Java side:
2. Create model for login request;
3. Create model for login response;
4. Create controller for handle authorization requests;
4.1 Create method for call auth.c_auth_subcriber(i_login varchar, i_password varchar) from Java code;
5.  create test for checking authorization;
5.1 need to create a permanent test user;
5.2 unitTests.TestJunit: create @Test method - checkAuthTestUserPositive().
5.3 unitTests.TestJunit: create @Test method - checkAuthTestUserNegative().
6. Test on Heroku side
7. Commit on "db" and "api" branches.

**Comment by Snorri1986** [comment]
Task 1 - in progress

**Comment by Snorri1986** [comment]
01.12.2021 - regular daily commit: 7d17bc722434e31df70abc1d900d712c1b4cc8d0

**Comment by Snorri1986** [comment]
About task 5.1:
Login: LoyalUser
Password: LoyalPassword

**Comment by Snorri1986** [comment]
Abot task 5.2 and 5.3:
[ERROR] checkAuthTestUserPositive  Time elapsed: 0.009 s  <<< ERROR!
java.lang.NullPointerException: Cannot invoke "javax.persistence.EntityManager.createStoredProcedureQuery(String)" because "this.entityManager" is null
	at unitTests.TestJunit.checkAuthTestUserPositive(TestJunit.java:90)
-------------------------------------------------------------------------------
[ERROR] checkAuthTestUserNegative  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NullPointerException: Cannot invoke "javax.persistence.EntityManager.createStoredProcedureQuery(String)" because "this.entityManager" is null
	at unitTests.TestJunit.checkAuthTestUserNegative(TestJunit.java:100)

**Comment by Snorri1986** [comment]
About task 6:
Error http 503 Service Unavailable

**Comment by Snorri1986** [comment]
Task is done
